##################################################################################
##################         Modify ansible config        ##########################
##################################################################################

- name: Change FTP default port to 2121
  lineinfile:
    path: /etc/vsftpd.conf
    regexp: '^listen_port='
    line: listen_port=2121

- name: Enable any form of WRITE operation of ftp.
  lineinfile:
    path: /etc/vsftpd.conf
    regexp: '^#write_enable='
    line: write_enable=YES

- name: enable implicit_ssl for securely transfer
  lineinfile:
    path: /etc/vsftpd.conf
    regexp: '^implicit_ssl='
    line: implicit_ssl=YES

- name: enable ssl for securely transfer
  lineinfile:
    path: /etc/vsftpd.conf
    regexp: '^ssl_enable='
    line: ssl_enable=YES

- name: pass generated cert file
  lineinfile:
    path: /etc/vsftpd.conf
    regexp: '^rsa_cert_file='
    line: rsa_cert_file=/etc/ssl/certs/vsftpd.pem

- name: pass generated key file
  lineinfile:
    path: /etc/vsftpd.conf
    regexp: '^rsa_private_key_file='
    line: rsa_private_key_file=/etc/ssl/private/vsftpd.key
#
- name: enable log for monitoring
  lineinfile:
    path: /etc/vsftpd.conf
    regexp: '^log_ftp_protocol='
    line: log_ftp_protocol=YES
#
#- name: set the root location for file storage
#  lineinfile:
#    path: /etc/vsftpd.conf
#    regexp: '^local_root='
#    line: local_root="/home/test/ftp"
#
- name: specify the passive port for the communication
  blockinfile:
    path: /etc/vsftpd.conf
    backup: yes
    block: |
      #enabling passive communication
      pasv_enable=YES
      pasv_min_port=40000
      pasv_max_port=50000
      #enabling Chroot to restrict FTP users to their home directory
      userlist_enable=YES
      userlist_file=/etc/vsftpd.userlist
      allow_writeable_chroot=YES
      userlist_deny=NO

- name: restart vsftpd
  service:
    name: vsftpd
    state: restarted